"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OBJECT_MUST_BE_IN_SHOPIFY_TAG = exports.FILTERS_MUST_BE_IN_SHOPIFY_TAG = exports.VARIABLES_NAME = void 0;
exports.VARIABLES_NAME = [
    'templates',
    'template',
    'request',
    'sections',
    'section',
    'localization',
    'form',
    'orders',
    'order',
    'customer',
    'line_item',
    'paginate',
    'part',
    'gift_cards',
    'gift_card',
    'media',
    'routes',
    'route',
    'block',
    'search',
    'general',
    // https://shopify.dev/api/liquid/objects#images
    'collections',
    'collection',
    'product',
    'all_products',
    'blogs',
    'blog',
    'articles',
    'article',
    'cart',
    'shop',
    'settings',
    'setting',
    'recommendations',
    'recommendation',
    'canonical_url',
    'current_page',
    'current_tags',
    'current_tag',
    'linklists',
    'linklist',
    'handle',
    'images',
    'image',
    'pages',
    'page',
    'page_description',
    'page_title',
    'powered_by_link',
    'scripts',
    'script',
    'theme',
    'content_for_header',
    'content_for_index',
    'content_for_layout',
    'additional_checkout_buttons',
    'content_for_additional_checkout_buttons',
];
exports.FILTERS_MUST_BE_IN_SHOPIFY_TAG = ['t', 'weight_with_unit', 'money'];
exports.OBJECT_MUST_BE_IN_SHOPIFY_TAG = ['content_for_index', 'content_for_layout', 'content_for_header', 'powered_by_link'];
