"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.form = void 0;
var activate_customer_password_1 = require("./activate_customer_password");
var contact_1 = require("./contact");
var create_customer_1 = require("./create_customer");
var customer_1 = require("./customer");
var customer_address_1 = require("./customer_address");
var customer_login_1 = require("./customer_login");
var guest_login_1 = require("./guest_login");
var new_comment_1 = require("./new_comment");
var product_1 = require("./product");
var recover_customer_password_1 = require("./recover_customer_password");
var reset_customer_password_1 = require("./reset_customer_password");
var payment_button_1 = require("./special_html_filters/payment_button");
var payment_terms_1 = require("./special_html_filters/payment_terms");
var storefront_password_1 = require("./storefront_password");
var form = function (liquid) {
    var _liquid = (0, activate_customer_password_1.activate_customer_password)(liquid);
    _liquid = (0, contact_1.contact)(_liquid);
    _liquid = (0, create_customer_1.create_customer)(_liquid);
    _liquid = (0, customer_1.customer)(_liquid);
    _liquid = (0, customer_address_1.customer_address)(_liquid);
    _liquid = (0, customer_login_1.customer_login)(_liquid);
    _liquid = (0, guest_login_1.guest_login)(_liquid);
    _liquid = (0, new_comment_1.new_comment)(_liquid);
    _liquid = (0, payment_button_1.payment_button)(_liquid);
    _liquid = (0, payment_terms_1.payment_terms)(_liquid);
    _liquid = (0, product_1.product)(_liquid);
    _liquid = (0, recover_customer_password_1.recover_customer_password)(_liquid);
    _liquid = (0, reset_customer_password_1.reset_customer_password)(_liquid);
    _liquid = (0, storefront_password_1.storefront_password)(_liquid);
    return _liquid.replace(/{%\s*endform\s*%}/gm, '</form>');
};
exports.form = form;
